### PR TITLE
Allow overriding OrbitControls Properties

### PR DESCRIPTION
**Pull request by alaarihan**
I needed to disable zoom so I thought it's good to have a prop to override OrbitControls Properties
https://threejs.org/docs/#examples/en/controls/OrbitControls

Please tell me if you need any updates before merge.

This will fix these issues:
#97 #86

### CODE REVIEW

**Comment by hujiulong** [comment]
Thanks!

**Comment by alaarihan** [comment]
Thank you!

**Comment by mhp-borisbojic** [comment]
@alaarihan @hujiulong 

This doesn't seem to work correctly? From the code and documentation, I understand that the prop "controlsOption" expects an object with parameters from the OrbitControls, for example:

```
<template>
  <div id="app">
    <model-gltf
      src="/assets/objects/Wing2_optimized.gltf"
      :controlsOptions="controlsOptions"
    />
  </div>
</template>

<script>
import { ModelGltf } from 'vue-3d-model';
export default {
  name: 'App',

  components: {
    ModelGltf
  },

  data: function() {
    return {
      controlsOptions: {
        enablePan: false,
        enableZoom: false
      }
    }
  },

}
</script>

<style lang="scss">
#app {
  margin: 0 auto;
  width: 80%;
  border: 1px solid red;
}
</style>
```

I want to disable any zoom, but even with these settings, the zoom still works (with mouse and touchpad).

What am I doing wrong?

**Comment by alaarihan** [comment]
@mhp-borisbojic This change has merged but it haven't released yet, so you need to use the master brunch of this repository to use this feature or you can wait for @hujiulong to release it.

**Pull request merged**
