### PR TITLE
updated background example

### PR DESCRIPTION
**Pull request by creazy231**
For some reasons it seams that Vue does not interpret any uppercase characters as lowercase.
fix https://github.com/hujiulong/vue-3d-model/issues/66

### CODE REVIEW

**Comment by hujiulong** [comment]
Thanks, the code here also needs to be modified.
https://github.com/hujiulong/vue-3d-model/blob/3a499018f8fb9cd81cfb5e726289113b17bea2e2/examples/pages/demo-background.vue#L84-L85
https://github.com/hujiulong/vue-3d-model/blob/3a499018f8fb9cd81cfb5e726289113b17bea2e2/examples/pages/demo-background.vue#L123-L124

**Comment by creazy231** [comment]
the problem with uppercase characters seems to appear only by using html injected vue. If you use vue combined with webpack there is no problem with `backgroundAlpha`and `backgroundColor`.

**Comment by hujiulong** [comment]
@creazy231 Oh, I see, then we only need to modify this place
https://github.com/hujiulong/vue-3d-model/blob/3a499018f8fb9cd81cfb5e726289113b17bea2e2/examples/pages/demo-background.vue#L123-L124

we'd better modify them together.

**Comment by creazy231** [comment]
Did I misunderstand something? That're exactly the lines I changed in my request? :D

**Comment by hujiulong** [comment]
emmm.. let me merge it first.

**Pull request merged**
